status messages and exit codes fixed

diff --git a/wpas b/wpas
--- a/wpas
+++ b/wpas
@@ -2,7 +2,7 @@
 set -eu
 
 interface=wlp58s0
-[[ -z "$interface" ]] && echo "Error: network interface  not defined" && exit 1
+[[ -z "$interface" ]] && echo "Error: network interface not defined" && exit 1
 
 scan_results="/var/tmp/scan_results.txt"
 
@@ -21,7 +21,12 @@ function extract_info {
 }
 
 function extract_ssid {
-  (grep -E "^$1\).*" < "$scan_results") | awk -F "'" '{ print $2 }'
+  if [[ "$1" =~ ^[0-9]$ ]]
+  then
+    grep -E "^$1\).*" 
+  else
+    grep -i "$1" 
+  fi < "$scan_results" | awk -F "'" '{ print $2 }'
 }
 
 function find_wpa_net_id {
@@ -33,7 +38,8 @@ function find_wpa_net_id {
     wpa_cli -i "$interface" list_networks |
       tail -n +2 |
       grep -i "$ssid" |
-      awk '{ print $1 }'
+      awk '{ print $1 }' |
+      head -n 1
   fi
 }
 
@@ -45,6 +51,17 @@ function usage {
   echo "    Connect to network by ID/SSID"
   echo "  wpa_select a [ID]"
   echo "    Add network by ID"
+}
+
+function print_status {
+  if [[ "$1" = 0 ]]
+  then
+    printf "\e[32m%s\e[39m\n" "OK"
+    exit 0
+  else
+    printf "\e[31m%s\e[39m\n" "FAIL"
+    exit 1
+  fi
 }
 
 case "$1" in
@@ -62,11 +79,15 @@ case "$1" in
     ;;
   c)
     id=$(find_wpa_net_id "$2")
+    ssid=$(extract_ssid "$2")
 
     if [ -n "$id" ]
     then
-      wpa_cli -i "$interface" enable_network "$id" &&
-      wpa_cli -i "$interface" select_network "$id"
+      echo -n "Connecting to $ssid..."
+      wpa_cli -i "$interface" enable_network "$id" | grep OK > /dev/null &&
+      wpa_cli -i "$interface" select_network "$id" | grep OK > /dev/null
+
+      print_status $?
       exit $?
     else
       echo "Access point not configured. Add new entry? (y/n)"
@@ -74,9 +95,9 @@ case "$1" in
 
       if [[ "$res" = y ]]
       then
-	wpa_select a "$2"
+      	wpa_select a "$2"
       else
-	exit 0
+      	exit 0
       fi
     fi
     ;;
@@ -85,10 +106,14 @@ case "$1" in
     read  -p 'psk: ' psk
     id=$(wpa_cli -i "$interface" add_network)
 
-    wpa_cli -i "$interface" set_network "$id" ssid "\"$ssid\"" &&
-    wpa_cli -i "$interface" set_network "$id" psk "\"$psk\"" &&
-    wpa_cli -i "$interface" save_config
+    echo -n "Adding $ssid..."
+    wpa_cli -i "$interface" set_network "$id" ssid "\"$ssid\"" | 
+      grep OK > /dev/null &&
+      wpa_cli -i "$interface" set_network "$id" psk "\"$psk\"" |
+      grep OK > /dev/null &&
+      wpa_cli -i "$interface" save_config | grep OK > /dev/null
 
+    print_status $?
     exit $?
     ;;
   h)
